version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      DEBUG: "false"

    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - backend_network

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mydefaultuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mydefaultpassword}
      POSTGRES_DB: ${POSTGRES_DB:-mydefaultdb}
    ports:
      - "5432:5432"
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
