"""vote, reports schema changes

Revision ID: 0f1f019ca394
Revises: 0d920d82e143
Create Date: 2025-03-25 17:29:55.726109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f1f019ca394'
down_revision: Union[str, None] = '0d920d82e143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('reports', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=8, scale=6),
               existing_nullable=True)
    op.alter_column('reports', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=9, scale=6),
               existing_nullable=True)
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.alter_column('reports', 'longitude',
               existing_type=sa.Numeric(precision=9, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('reports', 'latitude',
               existing_type=sa.Numeric(precision=8, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('reports', 'user_id')
    # ### end Alembic commands ###
