"""add ai image review related columns to report photos

Revision ID: 7d1ee8a50ef3
Revises: 8704e7ced520
Create Date: 2025-05-15 20:17:13.953586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1ee8a50ef3'
down_revision: Union[str, None] = '8704e7ced520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reportphotos', sa.Column('ai_score', sa.Integer(), nullable=True))
    op.add_column('reportphotos', sa.Column('ai_labels', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reportphotos', 'ai_labels')
    op.drop_column('reportphotos', 'ai_score')
    # ### end Alembic commands ###
