"""Add report's vote positive/negative counting

Revision ID: 8704e7ced520
Revises: 46858aec6abc
Create Date: 2025-04-11 22:37:52.250393

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8704e7ced520"
down_revision: Union[str, None] = "46858aec6abc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_notifications_id"), "notifications", ["id"], unique=False)
    op.add_column(
        "reports",
        sa.Column("votes_pos", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "reports",
        sa.Column("votes_neg", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column(
        "users",
        "phone_number",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.create_unique_constraint(None, "users", ["phone_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users",
        "phone_number",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.drop_column("reports", "votes_neg")
    op.drop_column("reports", "votes_pos")
    op.drop_index(op.f("ix_notifications_id"), table_name="notifications")
    # ### end Alembic commands ###
